### ISSUE TITLE
[BUG] Missing assets in search.css

### ISSUE THREAD

**Issue by Sudershan29** [globus/django-globus-portal-framework#232]
When running `python manage.py collectstatic` on a project that uses v3 template of the dgpf portal, there is a missing asset error traces up, and does not let the assets to build.

**Stack Trace**

```
python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/ubuntu/globus-presentation-portal/django_globus_presentation_portal/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Post-processing 'globus-portal-framework/v3/search.css' failed!

Traceback (most recent call last):
  File "/home/ubuntu/globus-presentation-portal/django_globus_presentation_portal/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/globus-presentation-portal/django_globus_presentation_portal/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
                ^^^^^^^^^^^^^^
  File "/home/ubuntu/gpp/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'globus-portal-framework/images/mag_glass.svg' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x74dec28abe30>.

The CSS file 'globus-portal-framework/v3/search.css' references a file which could not be found:
  globus-portal-framework/images/mag_glass.svg

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by hategan** [comment]
Indeed. I have a few patches that fix these, but was waiting to check the file manager. Anyway, the FM seems fine.
